### PR TITLE
add support for deeply nested schemaField definitions

### PR DESCRIPTION
**Pull request by EvavW**

### CODE REVIEW

**Review by riordan — APPROVED** [review]
Group review

**Comment by waligob** [comment]
Awesome. Do you know if this change will allow us to successfully deploy the [arc_content_schema_prod.json](https://github.com/phillymedia/inq-data-resources/blob/ea6591ced40dce0450ddee48b7a12045fb282335/tasks/catalog/schemas/arc_content_schema_prod.json) schema? We had to deploy that schema [by hand](https://github.com/phillymedia/inq-data-resources#manual-deployment-of-external-tables) because we couldn't get the schema definition file working correctly, but I think this addresses the issue we encountered there.

**Comment by ajonesINQ** [comment]
It was something about not being able to understand the schema. Which always confused me b/c when I created the table directly from GCP console it worked fine. I'll see if I can dig up the old airflow runs to be sure.

**Comment by ajonesINQ** [comment]
I had to make a change to the schema today. But I will set up a dummy test and run it tomorrow to see if it works for this

**Pull request merged**
